-- =====================================================================
-- RESPALDO · public.eventos del proyecto Website (tpcbzddxwqypvckvvbfa)
-- Tomado el 2026-09-09, antes de instalar el schema finanzas.
--
-- 13 filas de producción: son los eventos que sirve somostrufas.org.
-- El plan Free de Supabase no incluye backups, así que este archivo es
-- el único respaldo de esa tabla en ese momento.
--
-- Restauración: ejecutar como owner. Repone las 13 filas por su id y
-- deja intacto lo que se haya agregado después (incluida EVT-GENERAL).
-- Los datos van como JSON y se vuelcan con jsonb_populate_recordset,
-- así que los tipos los resuelve la propia definición de la tabla y no
-- hay riesgo de que un literal mal formateado corrompa una fila.
-- =====================================================================

begin;

insert into public.eventos
select * from jsonb_populate_recordset(null::public.eventos, $respaldo$
[
  {
    "id": "circuito-trufas-2026-3",
    "cta": null,
    "url": "/esports/circuito-valorant-norte-2026-3",
    "abre": "2026-11-25T05:00:00+00:00",
    "home": true,
    "tipo": "torneo",
    "juego": "Valorant",
    "marca": null,
    "serie": null,
    "creado": "2026-09-08T20:38:34.013137+00:00",
    "enlace": "esports",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/Valorant-Circuitos.webp",
    "inicio": "2027-01-01T04:59:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Circuito Trufas 2026-3",
    "destino": "Esports",
    "esports": true,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": "LATAM Norte",
    "titulo_en": null,
    "actualizado": "2026-09-08T20:38:34.013137+00:00",
    "descripcion": "Conoce formatos, fechas, premios y costos antes de inscribirte.",
    "subtitulo_en": "LATAM North",
    "descripcion_en": "Check formats, dates, prizes and costs before signing up.",
    "duracion_horas": 24
  },
  {
    "id": "escaladas-alocadas-2026-09-04",
    "cta": {
      "hero": "Unirme al Discord",
      "abierto": "Unirme al Discord"
    },
    "url": "https://discord.gg/TgCQX39FX?event=1544205059833995345",
    "abre": null,
    "home": true,
    "tipo": null,
    "juego": "PEAK",
    "marca": null,
    "serie": null,
    "creado": "2026-09-04T02:30:29.755812+00:00",
    "enlace": "discord",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/escaladas-alocadas.webp",
    "inicio": "2026-09-05T02:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Escaladas Alocadas",
    "destino": "Discord",
    "esports": false,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": "Crazy Climbs",
    "actualizado": "2026-09-04T02:30:29.755812+00:00",
    "descripcion": "Llega tan lejos como puedas con la comunidad.",
    "subtitulo_en": null,
    "descripcion_en": "Climb as high as you can with the community.",
    "duracion_horas": 3
  },
  {
    "id": "noche-de-camaleones-2026-09-03",
    "cta": {
      "hero": "Unirme al Discord",
      "abierto": "Unirme al Discord"
    },
    "url": "https://discord.gg/TgCQX39FX?event=1544201694672588960",
    "abre": null,
    "home": true,
    "tipo": null,
    "juego": "Meccha Chameleon",
    "marca": null,
    "serie": null,
    "creado": "2026-09-04T02:30:29.755812+00:00",
    "enlace": "discord",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/noche-de-camaleones.webp",
    "inicio": "2026-09-04T02:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Noche de Camaleones",
    "destino": "Discord",
    "esports": false,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": "Chameleon Night",
    "actualizado": "2026-09-04T02:30:29.755812+00:00",
    "descripcion": "Camúflate tan bien como puedas para no ser eliminado.",
    "subtitulo_en": null,
    "descripcion_en": "Blend in as well as you can so you do not get eliminated.",
    "duracion_horas": 3
  },
  {
    "id": "noche-de-impostores-2026-08-28",
    "cta": {
      "hero": "Unirme al Discord",
      "abierto": "Unirme al Discord"
    },
    "url": "https://discord.gg/TgCQX39FX?event=1486436211043074128",
    "abre": null,
    "home": true,
    "tipo": null,
    "juego": "Among Us",
    "marca": null,
    "serie": "noche-de-impostores",
    "creado": "2026-08-25T04:07:05.588802+00:00",
    "enlace": "discord",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/noche-de-impostores.webp",
    "inicio": "2026-08-29T02:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Noche de Impostores",
    "destino": "Discord",
    "esports": false,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": "Impostor Night",
    "actualizado": "2026-08-26T07:47:03.305548+00:00",
    "descripcion": "¿Lograrás descubrir al impostor antes de que maten a todos?",
    "subtitulo_en": null,
    "descripcion_en": "Can you spot the impostor before everyone gets taken out?",
    "duracion_horas": 3
  },
  {
    "id": "noche-de-impostores-2026-09-11",
    "cta": {
      "hero": "Unirme al Discord",
      "abierto": "Unirme al Discord"
    },
    "url": "https://discord.gg/TgCQX39FX?event=1486436211043074128",
    "abre": null,
    "home": true,
    "tipo": null,
    "juego": "Among Us",
    "marca": null,
    "serie": "noche-de-impostores",
    "creado": "2026-08-25T04:39:04.927795+00:00",
    "enlace": "discord",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/noche-de-impostores.webp",
    "inicio": "2026-09-12T02:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Noche de Impostores",
    "destino": "Discord",
    "esports": false,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": "Impostor Night",
    "actualizado": "2026-08-26T07:47:03.875646+00:00",
    "descripcion": "¿Lograrás descubrir al impostor antes de que maten a todos?",
    "subtitulo_en": null,
    "descripcion_en": "Can you spot the impostor before everyone gets taken out?",
    "duracion_horas": 3
  },
  {
    "id": "noche-de-karaoke-2026-08-26",
    "cta": {
      "hero": "Unirme al Discord",
      "abierto": "Unirme al Discord"
    },
    "url": "https://discord.gg/TgCQX39FX?event=1470966037917729001",
    "abre": null,
    "home": true,
    "tipo": null,
    "juego": "Just Chatting · Karaoke",
    "marca": null,
    "serie": "noche-de-karaoke",
    "creado": "2026-08-25T03:45:25.983789+00:00",
    "enlace": "discord",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/noche-de-karaoke.webp",
    "inicio": "2026-08-27T02:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Noche de Karaoke",
    "destino": "Discord",
    "esports": false,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": "Karaoke Night",
    "actualizado": "2026-08-26T07:47:04.45023+00:00",
    "descripcion": "Una noche para cantar, reír y disfrutar tus canciones favoritas.",
    "subtitulo_en": null,
    "descripcion_en": "A night to sing, laugh and enjoy your favourite songs.",
    "duracion_horas": 3
  },
  {
    "id": "noche-de-karaoke-2026-09-02",
    "cta": {
      "hero": "Unirme al Discord",
      "abierto": "Unirme al Discord"
    },
    "url": "https://discord.gg/TgCQX39FX?event=1470966037917729001",
    "abre": null,
    "home": true,
    "tipo": null,
    "juego": "Just Chatting · Karaoke",
    "marca": null,
    "serie": "noche-de-karaoke",
    "creado": "2026-08-25T04:39:03.777154+00:00",
    "enlace": "discord",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/noche-de-karaoke.webp",
    "inicio": "2026-09-03T02:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Noche de Karaoke",
    "destino": "Discord",
    "esports": false,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": "Karaoke Night",
    "actualizado": "2026-08-26T07:47:05.024748+00:00",
    "descripcion": "Una noche para cantar, reír y disfrutar tus canciones favoritas.",
    "subtitulo_en": null,
    "descripcion_en": "A night to sing, laugh and enjoy your favourite songs.",
    "duracion_horas": 3
  },
  {
    "id": "roblox-insano-2026-08-30",
    "cta": {
      "hero": "Unirme al Discord",
      "abierto": "Unirme al Discord"
    },
    "url": "https://discord.gg/TgCQX39FX?event=1515932629495451729",
    "abre": null,
    "home": true,
    "tipo": null,
    "juego": "Roblox",
    "marca": null,
    "serie": "roblox-insano",
    "creado": "2026-08-25T04:07:06.132801+00:00",
    "enlace": "discord",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/roblox-insano.webp",
    "inicio": "2026-08-31T02:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Roblox Insano",
    "destino": "Discord",
    "esports": false,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": "Roblox Madness",
    "actualizado": "2026-08-26T07:47:05.572668+00:00",
    "descripcion": "Jueguito aleatorio elegido por los participantes.",
    "subtitulo_en": null,
    "descripcion_en": "A random game, picked by whoever shows up.",
    "duracion_horas": 3
  },
  {
    "id": "roblox-insano-2026-09-13",
    "cta": {
      "hero": "Unirme al Discord",
      "abierto": "Unirme al Discord"
    },
    "url": "https://discord.gg/TgCQX39FX?event=1515932629495451729",
    "abre": null,
    "home": true,
    "tipo": null,
    "juego": "Roblox",
    "marca": null,
    "serie": "roblox-insano",
    "creado": "2026-08-25T04:39:06.192232+00:00",
    "enlace": "discord",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/roblox-insano.webp",
    "inicio": "2026-09-14T02:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Roblox Insano",
    "destino": "Discord",
    "esports": false,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": "Roblox Madness",
    "actualizado": "2026-08-26T07:47:06.154686+00:00",
    "descripcion": "Jueguito aleatorio elegido por los participantes.",
    "subtitulo_en": null,
    "descripcion_en": "A random game, picked by whoever shows up.",
    "duracion_horas": 3
  },
  {
    "id": "sorteo-juego-eleccion",
    "cta": {
      "hero": "Participar en el sorteo",
      "abierto": "Participar"
    },
    "url": "https://www.instant-gaming.com/es/giveaway/somostrufas",
    "abre": null,
    "home": true,
    "tipo": "sorteo",
    "juego": null,
    "marca": null,
    "serie": null,
    "creado": "2026-08-26T07:22:05.868932+00:00",
    "enlace": "externo",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/sorteo-juego-eleccion.webp",
    "inicio": "2026-08-26T05:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Sorteo: 1 Juego a Elección",
    "destino": "Instant Gaming",
    "esports": true,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": "Giveaway: 1 Game of Your Choice",
    "actualizado": "2026-08-31T16:09:12.547722+00:00",
    "descripcion": "Ganarás el videojuego que tú elijas, sin importar la plataforma o su costo.",
    "subtitulo_en": null,
    "descripcion_en": "You'll win the video game of your choice, whatever the platform or the price.",
    "duracion_horas": 736
  },
  {
    "id": "sorteo-nitro-2026-08-31",
    "cta": {
      "hero": "Participar en el sorteo",
      "abierto": "Participar"
    },
    "url": "https://discord.com/events/335437867008655360/1541121386708344902",
    "abre": null,
    "home": true,
    "tipo": "sorteo",
    "juego": null,
    "marca": null,
    "serie": "sorteo-nitro",
    "creado": "2026-08-25T03:56:30.17506+00:00",
    "enlace": "discord",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/sorteo-nitro.webp",
    "inicio": "2026-08-25T05:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Sorteo de Nitro",
    "destino": "Discord",
    "esports": true,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": "Nitro Giveaway",
    "actualizado": "2026-08-31T16:09:12.547722+00:00",
    "descripcion": "Sorteamos esto y mucho más en nuestro Discord cada mes.",
    "subtitulo_en": null,
    "descripcion_en": "We give away this and much more on our Discord every month.",
    "duracion_horas": 162
  },
  {
    "id": "sorteo-nitro-2026-09-30",
    "cta": {
      "hero": "Participar en el sorteo",
      "abierto": "Participar"
    },
    "url": "https://discord.com/events/335437867008655360/1544746620644757664",
    "abre": null,
    "home": true,
    "tipo": "sorteo",
    "juego": null,
    "marca": null,
    "serie": "sorteo-nitro",
    "creado": "2026-09-04T02:30:29.755812+00:00",
    "enlace": "discord",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/sorteo-nitro.webp",
    "inicio": "2026-09-03T05:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Sorteo de Nitro",
    "destino": "Discord",
    "esports": false,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": "Nitro Giveaway",
    "actualizado": "2026-09-04T02:30:29.755812+00:00",
    "descripcion": "Mejora tu experiencia en Discord con Nitro.",
    "subtitulo_en": null,
    "descripcion_en": "Upgrade your Discord experience with Nitro.",
    "duracion_horas": 666
  },
  {
    "id": "sorteo-valorant-points-2026-09-20",
    "cta": null,
    "url": "https://discord.com/channels/335437867008655360/1431820966492639293",
    "abre": null,
    "home": true,
    "tipo": "sorteo",
    "juego": null,
    "marca": null,
    "serie": null,
    "creado": "2026-08-31T16:04:48.750333+00:00",
    "enlace": "discord",
    "imagen": "https://tpcbzddxwqypvckvvbfa.supabase.co/storage/v1/object/public/eventos/sorteo-valorant-points.webp",
    "inicio": "2026-08-31T05:00:00+00:00",
    "oculto": false,
    "plazas": null,
    "titulo": "Sorteo de Valorant Points",
    "destino": "Discord",
    "esports": true,
    "metrica": null,
    "destacado": false,
    "inscritos": 0,
    "subtitulo": null,
    "titulo_en": null,
    "actualizado": "2026-08-31T16:09:54.463833+00:00",
    "descripcion": "Únete al discord y conoce los requisitos para participar.",
    "subtitulo_en": null,
    "descripcion_en": null,
    "duracion_horas": 498
  }
]
$respaldo$)
on conflict (id) do update set
  titulo = excluded.titulo,             descripcion = excluded.descripcion,
  imagen = excluded.imagen,             inicio = excluded.inicio,
  duracion_horas = excluded.duracion_horas, abre = excluded.abre,
  destino = excluded.destino,           url = excluded.url,
  enlace = excluded.enlace,             juego = excluded.juego,
  metrica = excluded.metrica,           cta = excluded.cta,
  marca = excluded.marca,               oculto = excluded.oculto,
  plazas = excluded.plazas,             inscritos = excluded.inscritos,
  titulo_en = excluded.titulo_en,       descripcion_en = excluded.descripcion_en,
  serie = excluded.serie,               destacado = excluded.destacado,
  tipo = excluded.tipo,                 esports = excluded.esports,
  subtitulo = excluded.subtitulo,       subtitulo_en = excluded.subtitulo_en,
  home = excluded.home;

-- Debe devolver 13 o más (13 originales, más EVT-GENERAL si ya se instaló finanzas)
select count(*) as filas_totales,
       count(*) filter (where not oculto) as visibles_en_la_portada
from public.eventos;

-- Revisar el resultado antes de confirmar.
-- commit;
rollback;
